language: cpp
compiler:
  - gcc
  - clang
 
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - kalakris-cmake
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - cmake
  
script: 
  - mkdir build && cd build && cmake .. --debug-output && make VERBOSE=1
os:
  - linux
